version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3


jobs:
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["6e:8a:a8:6d:c2:09:cb:72:23:9e:c7:dd:fc:5d:d0:ff"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible gzip openssh-client
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml

workflows:
  my_workflows:
    jobs:
      - smoke_test
      # - configure_infrastructure